name: Claude Code
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  claude-response:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4

      # Claude Code 액션 실행
      - uses: anthropics/claude-code-action@beta
        with:
          # 인증: 둘 중 하나 선택
          # 또는
          oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # 선택 구성(필요 시):
          trigger: "on-comment" # 코멘트 기반 트리거 등
          pr_review: "auto" # PR 리뷰 자동 응답
          max_tokens: "2000"
